import numpy as np
from numpy.typing import NDArray
from typing import Optional

class RawImage:
    @staticmethod
    def open(path: str) -> "RawImage": ...

    def __enter__(self) -> "RawImage": ...
    def __exit__(self, exc_type, exc_value, traceback) -> None: ...
    def close(self) -> None: ...
    def is_closed(self) -> bool: ...

    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def bps(self) -> int: ...
    @property
    def cpp(self) -> int: ...
    @property
    def make(self) -> str: ...
    @property
    def model(self) -> str: ...
    @property
    def clean_make(self) -> str: ...
    @property
    def clean_model(self) -> str: ...
    @property
    def cfa_pattern(self) -> str: ...
    @property
    def cropped_cfa_pattern(self) -> Optional[str]: ...
    @property
    def wb_coeffs(self) -> tuple[float, float, float, float]: ...
    @property
    def active_area(self) -> Optional[tuple[int, int, int, int]]: ...
    @property
    def crop_area(self) -> Optional[tuple[int, int, int, int]]: ...
    @property
    def orientation(self) -> str: ...
    @property
    def whitelevel(self) -> list[int]: ...
    @property
    def blacklevel(self) -> dict: ...
    @property
    def blackareas(self) -> list[tuple[int, int, int, int]]: ...
    @property
    def photometric(self) -> str: ...
    @property
    def xyz_to_cam(self) -> list[list[float]]: ...
    @property
    def color_matrix(self) -> dict[str, list[float]]: ...
    @property
    def dng_tags(self) -> dict[int, str]: ...

    def raw_data(self) -> NDArray[np.uint16]: ...
    def raw_data_f32(self) -> NDArray[np.float32]: ...
    def cropped_raw_data(self) -> NDArray[np.uint16]: ...
    def __repr__(self) -> str: ...

def decode(path: str) -> RawImage: ...

__version__: str
